---

# hosts: Lista de hosts en donde se ejecutar치 el play. 

  hosts:
  gather_facts: False

# vars: Aquellos que se aplicar치n al play.

  variable: 

# tasks: Lista todas las tareas que se ejecutar치n dentro del play.

  task:

# handlers: Lista los handlers que son ejecutado como notificaci칩n de una tarea.

  handlers:

# roles: Lista de roles a ser importados dentro del play

  roles:

...
