---

- name: Instalacion de Apache2
  hosts: debian
  become: yes
  become_user: debian_user

  tasks:
    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Iniciar y habilitar servicio
      service:
        name: apache2
        state: started
        enabled: yes
