---

- name: Gesti칩n de servicio de Apache en m치quinas basadas en Debian
  hosts: debian_group
  become: True
  gather_facts: False

  tasks:
    - name: Instalar Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        #state: absent
      notify:
        Iniciar Servicio Apache2

  handlers:
    - name: Iniciar Servicio Apache2
      service:
        name: apache2
        state: started
        enabled: True


- name: Instalaci칩n de HTTPD en m치quinas basadas en redhat
  hosts: redhat_group
  become: True
  gather_facts: False

  tasks:
    - name: Instalar httpd
      dnf:
        name: httpd
        state: present
        #state: absent
      notify: Servicio corriendo

  handlers:
    - name: Servicio corriendo
      service:
        name: httpd
        state: started
        enabled: True
